# Generated by Django 5.0.1 on 2024-02-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="die",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=150)),
                ("LaunchDate", models.DateField()),
                ("ExpectedLife", models.IntegerField()),
                ("Product", models.CharField(max_length=150)),
                ("ActualLife", models.IntegerField()),
                ("DecommisionedOn", models.DateField()),
            ],
        ),
    ]
