# Generated by Django 5.0.1 on 2024-02-15 00:02

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DieManager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="die",
            name="DecommisionedOn",
        ),
        migrations.AddField(
            model_name="die",
            name="DecommissionedOn",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="die",
            name="Status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Active", "Active"),
                    ("Suspended", "Suspended"),
                    ("Decommissioned", "Decommissioned"),
                ],
                default="New",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="die",
            name="ActualLife",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RunDate", models.DateField(default=datetime.date(2024, 2, 15))),
                ("ExpectedUnits", models.IntegerField()),
                ("ActualUnits", models.IntegerField()),
                (
                    "ErrorRate",
                    models.DecimalField(
                        decimal_places=2,
                        default=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.comparison.Cast(
                                    models.IntegerField(), models.FloatField()
                                ),
                                "/",
                                django.db.models.functions.comparison.Cast(
                                    models.IntegerField(), models.FloatField()
                                ),
                            ),
                            "*",
                            models.Value(100),
                        ),
                        max_digits=4,
                    ),
                ),
                (
                    "Die",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="DieManager.die"
                    ),
                ),
            ],
        ),
    ]
