# Generated by Django 5.0.1 on 2024-02-15 00:18

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DieManager", "0002_remove_die_decommisionedon_die_decommissionedon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="ErrorRate",
            field=models.DecimalField(
                decimal_places=2,
                default=django.db.models.expressions.CombinedExpression(
                    models.Value(100),
                    "-",
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Cast(
                                models.IntegerField(), models.FloatField()
                            ),
                            "/",
                            django.db.models.functions.comparison.Cast(
                                models.IntegerField(), models.FloatField()
                            ),
                        ),
                        "*",
                        models.Value(100),
                    ),
                ),
                max_digits=4,
            ),
        ),
    ]
